"use client";

import React from "react";
import Link from "next/link";
import { Bot, Zap, Target, BarChart2, ArrowRight, Check } from "lucide-react";

export default function LandingPage() {
  const features = [
    { icon: <Bot size={16} />,      title: "AI Sales Copilot",        desc: "ChatGPT-style assistant trained on your pipeline. Ask anything, get instant intelligence." },
    { icon: <Target size={16} />,   title: "Intelligent Lead Scoring", desc: "AI-powered scoring ranks your leads by conversion probability in real time."             },
    { icon: <BarChart2 size={16} />, title: "Predictive Analytics",    desc: "Forecast revenue, identify at-risk deals, and surface high-impact opportunities."         },
    { icon: <Zap size={16} />,       title: "Auto Follow-Up Engine",   desc: "Personalized outreach generated by AI across Email, LinkedIn, and WhatsApp."              },
  ];

  const pricingPlans = [
    { name: "Starter",    price: "49",  features: ["5 Users", "1,000 Leads", "AI Copilot", "Email Follow-ups", "Basic Analytics"],                                  highlight: false },
    { name: "Pro",        price: "149", features: ["20 Users", "10,000 Leads", "AI Copilot + GPT-4", "All Channels", "Predictive Analytics", "Priority Support"], highlight: true  },
    { name: "Enterprise", price: "449", features: ["Unlimited Users", "Unlimited Leads", "Custom AI Models", "API Access", "Dedicated CSM", "SLA Guarantee"],       highlight: false },
  ];

  return (
    <div style={{ minHeight: "100vh", background: "#141414", color: "#e0e0e0", fontFamily: "Inter, system-ui, sans-serif" }}>

      {/* ── Navbar ── */}
      <nav style={{
        position: "fixed", top: 0, left: 0, right: 0, zIndex: 50,
        display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: "0 48px", height: 52,
        background: "#141414", borderBottom: "1px solid #1e1e1e",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <div style={{ width: 26, height: 26, borderRadius: 7, background: "#4f7bff", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <Bot size={13} color="#fff" />
          </div>
          <span style={{ fontSize: 14, fontWeight: 500, color: "#f0f0f0" }}>SalesMind AI</span>
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: 32 }}>
          {[
            { label: "Features", href: "#features" },
            { label: "Pricing",  href: "#pricing"  },
            { label: "Docs",     href: "/docs"     },
          ].map(({ label, href }) => (
            <a key={label} href={href} style={{ fontSize: 13, color: "#555", textDecoration: "none" }}
              onMouseEnter={e => ((e.currentTarget as HTMLElement).style.color = "#ccc")}
              onMouseLeave={e => ((e.currentTarget as HTMLElement).style.color = "#555")}
            >{label}</a>
          ))}
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <Link href="/login" style={{ fontSize: 13, color: "#555", textDecoration: "none", padding: "6px 12px" }}
            onMouseEnter={e => ((e.currentTarget as HTMLElement).style.color = "#ccc")}
            onMouseLeave={e => ((e.currentTarget as HTMLElement).style.color = "#555")}
          >Sign in</Link>
          <Link href="/dashboard" style={{
            fontSize: 13, fontWeight: 500, color: "#fff", textDecoration: "none",
            background: "#4f7bff", borderRadius: 7, padding: "7px 16px",
            transition: "opacity 0.15s",
          }}
            onMouseEnter={e => ((e.currentTarget as HTMLElement).style.opacity = "0.85")}
            onMouseLeave={e => ((e.currentTarget as HTMLElement).style.opacity = "1")}
          >Start free →</Link>
        </div>
      </nav>

      {/* ── Hero ── */}
      <section style={{ paddingTop: 140, paddingBottom: 100, paddingLeft: 48, paddingRight: 48, maxWidth: 760, margin: "0 auto" }}>
        <div style={{ fontSize: 12, color: "#4f7bff", marginBottom: 20, display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{ width: 5, height: 5, borderRadius: "50%", background: "#4f7bff", display: "inline-block" }} />
          Now with LLaMA 3.3 70B · Real-time intelligence
        </div>

        <h1 style={{ fontSize: 42, fontWeight: 600, color: "#f0f0f0", lineHeight: 1.2, marginBottom: 20, letterSpacing: "-0.02em" }}>
          AI-powered sales intelligence<br />
          <span style={{ color: "#4f7bff" }}>for modern teams.</span>
        </h1>

        <p style={{ fontSize: 15, color: "#555", lineHeight: 1.8, marginBottom: 36, maxWidth: 520 }}>
          SalesMind AI is the conversational AI workspace that helps your sales team close more deals.
          Like having ChatGPT trained on your entire pipeline.
        </p>

        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <Link href="/dashboard" style={{
            display: "inline-flex", alignItems: "center", gap: 6,
            fontSize: 13, fontWeight: 500, color: "#fff", textDecoration: "none",
            background: "#4f7bff", borderRadius: 7, padding: "10px 20px",
          }}>
            Start for free <ArrowRight size={13} />
          </Link>
          <Link href="/dashboard" style={{
            display: "inline-flex", alignItems: "center", gap: 6,
            fontSize: 13, color: "#555", textDecoration: "none",
            border: "1px solid #2a2a2a", borderRadius: 7, padding: "10px 20px",
          }}>
            View live demo
          </Link>
        </div>

        {/* App preview */}
        <div style={{ marginTop: 60, border: "1px solid #222", borderRadius: 10, overflow: "hidden" }}>
          {/* Browser chrome */}
          <div style={{ background: "#1a1a1a", borderBottom: "1px solid #222", padding: "10px 16px", display: "flex", alignItems: "center", gap: 10 }}>
            <div style={{ display: "flex", gap: 5 }}>
              {["#555","#555","#555"].map((c, i) => <div key={i} style={{ width: 10, height: 10, borderRadius: "50%", background: c }} />)}
            </div>
            <div style={{ flex: 1, display: "flex", justifyContent: "center" }}>
              <div style={{ fontSize: 11, color: "#444", background: "#141414", border: "1px solid #222", borderRadius: 5, padding: "3px 14px" }}>
                app.salesmind.ai/copilot
              </div>
            </div>
          </div>
          {/* Chat preview */}
          <div style={{ background: "#111", padding: 28, minHeight: 220 }}>
            {[
              { user: true,  text: "Which leads should I prioritize this week?" },
              { user: false, text: "Based on intent signals and ICP match, here are your top 3 accounts — Noah Williams at Stripe (Score: 94), Emma Watson at GitHub (Score: 88), and Liam Chen at Figma (Score: 81). All three have shown strong buy signals in the last 48 hours." },
              { user: true,  text: "Draft a follow-up email for Noah at Stripe." },
            ].map((m, i) => (
              <div key={i} style={{ display: "flex", flexDirection: m.user ? "row-reverse" : "row", gap: 10, marginBottom: 16 }}>
                <div style={{
                  width: 24, height: 24, borderRadius: 6, flexShrink: 0,
                  background: m.user ? "#2a2a2a" : "#4f7bff",
                  display: "flex", alignItems: "center", justifyContent: "center",
                  fontSize: 9, fontWeight: 600, color: "#fff",
                }}>
                  {m.user ? "SC" : <Bot size={11} color="#fff" />}
                </div>
                <div style={{
                  maxWidth: "72%", fontSize: 12, lineHeight: 1.7,
                  color: m.user ? "#888" : "#c8c8c8",
                  textAlign: m.user ? "right" : "left",
                }}>
                  {m.text}
                </div>
              </div>
            ))}
            <div style={{ display: "flex", gap: 10, alignItems: "center" }}>
              <div style={{ width: 24, height: 24, borderRadius: 6, background: "#4f7bff", display: "flex", alignItems: "center", justifyContent: "center" }}>
                <Bot size={11} color="#fff" />
              </div>
              <div style={{ display: "flex", gap: 4 }}>
                {[0, 1, 2].map(i => (
                  <span key={i} className="typing-dot" style={{ animationDelay: `${i * 150}ms` }} />
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Stats ── */}
      <section style={{ borderTop: "1px solid #1e1e1e", borderBottom: "1px solid #1e1e1e", padding: "40px 48px" }}>
        <div style={{ maxWidth: 760, margin: "0 auto", display: "flex", gap: 60 }}>
          {[
            { value: "2,400+", label: "Sales Teams" },
            { value: "89%",    label: "Avg Conversion Lift" },
            { value: "12M+",   label: "Leads Processed" },
            { value: "340%",   label: "Average ROI" },
          ].map(s => (
            <div key={s.label}>
              <div style={{ fontSize: 22, fontWeight: 600, color: "#f0f0f0" }}>{s.value}</div>
              <div style={{ fontSize: 12, color: "#555", marginTop: 3 }}>{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Features ── */}
      <section id="features" style={{ padding: "72px 48px" }}>
        <div style={{ maxWidth: 760, margin: "0 auto" }}>
          <p style={{ fontSize: 12, color: "#555", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 12 }}>Core Features</p>
          <h2 style={{ fontSize: 26, fontWeight: 600, color: "#f0f0f0", marginBottom: 8, letterSpacing: "-0.01em" }}>
            Everything your team needs to close faster.
          </h2>
          <p style={{ fontSize: 13, color: "#555", marginBottom: 40 }}>
            Built for modern sales teams. Every feature powered by next-generation AI.
          </p>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 1, border: "1px solid #1e1e1e", borderRadius: 10, overflow: "hidden" }}>
            {features.map((f, i) => (
              <div key={i} style={{
                padding: "24px 28px",
                background: "#141414",
                borderRight: i % 2 === 0 ? "1px solid #1e1e1e" : "none",
                borderBottom: i < 2 ? "1px solid #1e1e1e" : "none",
              }}>
                <div style={{ color: "#4f7bff", marginBottom: 12 }}>{f.icon}</div>
                <div style={{ fontSize: 14, fontWeight: 500, color: "#e8e8e8", marginBottom: 8 }}>{f.title}</div>
                <div style={{ fontSize: 13, color: "#555", lineHeight: 1.7 }}>{f.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pricing ── */}
      <section id="pricing" style={{ borderTop: "1px solid #1e1e1e", padding: "72px 48px" }}>
        <div style={{ maxWidth: 760, margin: "0 auto" }}>
          <p style={{ fontSize: 12, color: "#555", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 12 }}>Pricing</p>
          <h2 style={{ fontSize: 26, fontWeight: 600, color: "#f0f0f0", marginBottom: 40, letterSpacing: "-0.01em" }}>Simple, transparent pricing.</h2>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12 }}>
            {pricingPlans.map(plan => (
              <div key={plan.name} style={{
                padding: "24px",
                border: plan.highlight ? "1px solid #4f7bff" : "1px solid #1e1e1e",
                borderRadius: 10,
                background: plan.highlight ? "rgba(79,123,255,0.04)" : "transparent",
                display: "flex", flexDirection: "column",
              }}>
                {plan.highlight && (
                  <span style={{ fontSize: 10, color: "#4f7bff", border: "1px solid #4f7bff", borderRadius: 4, padding: "1px 7px", alignSelf: "flex-start", marginBottom: 14 }}>
                    POPULAR
                  </span>
                )}
                <div style={{ fontSize: 14, fontWeight: 500, color: "#e0e0e0", marginBottom: 8 }}>{plan.name}</div>
                <div style={{ marginBottom: 20 }}>
                  <span style={{ fontSize: 28, fontWeight: 600, color: "#f0f0f0" }}>${plan.price}</span>
                  <span style={{ fontSize: 13, color: "#555" }}>/mo</span>
                </div>
                <div style={{ flex: 1, marginBottom: 20 }}>
                  {plan.features.map(f => (
                    <div key={f} style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10, fontSize: 13, color: "#888" }}>
                      <Check size={12} style={{ color: "#4f7bff", flexShrink: 0 }} />
                      {f}
                    </div>
                  ))}
                </div>
                <Link href="/dashboard" style={{
                  display: "block", textAlign: "center", padding: "9px",
                  fontSize: 13, fontWeight: 500, textDecoration: "none",
                  borderRadius: 7,
                  background: plan.highlight ? "#4f7bff" : "transparent",
                  color: plan.highlight ? "#fff" : "#555",
                  border: plan.highlight ? "none" : "1px solid #2a2a2a",
                }}>
                  Get started
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Final CTA ── */}
      <section style={{ borderTop: "1px solid #1e1e1e", padding: "80px 48px", textAlign: "center" }}>
        <div style={{ maxWidth: 520, margin: "0 auto" }}>
          <h2 style={{ fontSize: 28, fontWeight: 600, color: "#f0f0f0", marginBottom: 12, letterSpacing: "-0.01em" }}>
            Your pipeline won't close itself.
          </h2>
          <p style={{ fontSize: 13, color: "#555", marginBottom: 28, lineHeight: 1.7 }}>
            Join 2,400+ teams using SalesMind AI to build a smarter, faster revenue engine.
          </p>
          <Link href="/dashboard" style={{
            display: "inline-flex", alignItems: "center", gap: 6,
            fontSize: 13, fontWeight: 500, color: "#fff", textDecoration: "none",
            background: "#4f7bff", borderRadius: 7, padding: "10px 24px",
          }}>
            Start building for free <ArrowRight size={13} />
          </Link>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer style={{ borderTop: "1px solid #1e1e1e", padding: "24px 48px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <div style={{ width: 20, height: 20, borderRadius: 5, background: "#4f7bff", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <Bot size={11} color="#fff" />
          </div>
          <span style={{ fontSize: 13, color: "#555" }}>SalesMind AI</span>
        </div>
        <p style={{ fontSize: 12, color: "#444" }}>© 2024 SalesMind AI. All rights reserved.</p>
      </footer>

    </div>
  );
}
