import { Lead, Activity, AnalyticsSummary, Insight } from "@/types";

export const mockLeads: Lead[] = [
  {
    id: 1,
    name: "Sarah Johnson",
    company: "TechFlow Inc",
    email: "sarah@techflow.com",
    phone: "+1 (555) 234-5678",
    lead_score: 94,
    deal_value: 85000,
    status: "Hot Lead",
    last_interaction: "2 hours ago",
    notes: "Very interested in enterprise plan. Demo scheduled for Friday.",
  },
  {
    id: 2,
    name: "Marcus Chen",
    company: "DataVault Co",
    email: "marcus@datavault.co",
    phone: "+1 (555) 345-6789",
    lead_score: 88,
    deal_value: 62000,
    status: "Hot Lead",
    last_interaction: "1 day ago",
    notes: "Budget confirmed. Needs legal review on contract.",
  },
  {
    id: 3,
    name: "Elena Rodriguez",
    company: "ScaleUp Labs",
    email: "elena@scaleuplabs.com",
    phone: "+1 (555) 456-7890",
    lead_score: 76,
    deal_value: 47000,
    status: "Warm Lead",
    last_interaction: "3 days ago",
    notes: "Evaluating 2 competitors. Strong fit for mid-market plan.",
  },
  {
    id: 4,
    name: "Raj Mehta",
    company: "Quantum Ventures",
    email: "raj@quantumv.io",
    phone: "+1 (555) 567-8901",
    lead_score: 68,
    deal_value: 38000,
    status: "Warm Lead",
    last_interaction: "5 days ago",
    notes: "On trial. Positive feedback from team. Needs pricing discussion.",
  },
  {
    id: 5,
    name: "Ava Thompson",
    company: "Nexus Digital",
    email: "ava@nexusdigital.com",
    phone: "+1 (555) 678-9012",
    lead_score: 61,
    deal_value: 34000,
    status: "Warm Lead",
    last_interaction: "1 week ago",
    notes: "Interested but slow decision process. Multiple stakeholders.",
  },
  {
    id: 6,
    name: "Jordan Lee",
    company: "Bright Future Co",
    email: "jordan@brightfuture.co",
    phone: "+1 (555) 789-0123",
    lead_score: 45,
    deal_value: 22000,
    status: "Cold Lead",
    last_interaction: "2 weeks ago",
    notes: "Initial interest but went quiet after pricing call.",
  },
  {
    id: 7,
    name: "James Wilson",
    company: "OldCo Corp",
    email: "james@oldcorp.com",
    phone: "+1 (555) 890-1234",
    lead_score: 32,
    deal_value: 28000,
    status: "Cold Lead",
    last_interaction: "3 weeks ago",
    notes: "Budget frozen. Check back in Q1.",
  },
  {
    id: 8,
    name: "Priya Patel",
    company: "StartRight LLC",
    email: "priya@startright.io",
    phone: "+1 (555) 901-2345",
    lead_score: 28,
    deal_value: 18000,
    status: "Cold Lead",
    last_interaction: "1 month ago",
    notes: "Switched priorities. Keep warm for next quarter.",
  },
  {
    id: 9,
    name: "Michael Torres",
    company: "Growth Engine",
    email: "michael@growthengine.ai",
    phone: "+1 (555) 012-3456",
    lead_score: 95,
    deal_value: 120000,
    status: "Closed",
    last_interaction: "2 weeks ago",
    notes: "Deal closed! Signed enterprise annual contract.",
  },
  {
    id: 10,
    name: "Lisa Park",
    company: "Momentum SaaS",
    email: "lisa@momentumsaas.com",
    phone: "+1 (555) 123-4567",
    lead_score: 91,
    deal_value: 75000,
    status: "Closed",
    last_interaction: "3 weeks ago",
    notes: "Successful implementation. Potential upsell in Q3.",
  },
];

export const mockActivities: Activity[] = [
  {
    id: 1,
    type: "meeting",
    title: "Discovery call with Sarah Johnson",
    description:
      "Discussed pain points and requirements. Strong buying signals. Budget of $85K confirmed.",
    lead_name: "Sarah Johnson",
    created_at: "2026-06-13T00:10:00Z",
  },
  {
    id: 2,
    type: "ai_action",
    title: "AI scored Marcus Chen at 88/100",
    description:
      "High urgency detected. Budget discussion indicates Q4 close. Recommended immediate demo scheduling.",
    lead_name: "Marcus Chen",
    created_at: "2026-06-12T22:30:00Z",
  },
  {
    id: 3,
    type: "follow_up",
    title: "Follow-up email sent to Elena Rodriguez",
    description:
      "Personalized email with competitor comparison and ROI calculator attached.",
    lead_name: "Elena Rodriguez",
    created_at: "2026-06-12T18:15:00Z",
  },
  {
    id: 4,
    type: "lead_update",
    title: "Raj Mehta upgraded to Warm Lead",
    description:
      "Trial feedback positive. Lead score increased from 55 to 68 after engagement analysis.",
    lead_name: "Raj Mehta",
    created_at: "2026-06-12T14:00:00Z",
  },
  {
    id: 5,
    type: "meeting",
    title: "Product demo with Ava Thompson",
    description:
      "30-min demo completed. Feature requests noted: advanced reporting and API integrations.",
    lead_name: "Ava Thompson",
    created_at: "2026-06-11T16:30:00Z",
  },
  {
    id: 6,
    type: "ai_action",
    title: "AI generated follow-up for Jordan Lee",
    description:
      "Personalized re-engagement email created based on previous interaction history.",
    lead_name: "Jordan Lee",
    created_at: "2026-06-11T10:00:00Z",
  },
  {
    id: 7,
    type: "lead_update",
    title: "Deal closed: Michael Torres",
    description:
      "Enterprise contract signed. $120K ARR. Implementation kick-off scheduled for next Monday.",
    lead_name: "Michael Torres",
    created_at: "2026-06-10T11:00:00Z",
  },
  {
    id: 8,
    type: "follow_up",
    title: "Onboarding email sent to Lisa Park",
    description: "Welcome sequence initiated. Customer success manager assigned.",
    lead_name: "Lisa Park",
    created_at: "2026-06-09T09:00:00Z",
  },
];

export const mockAnalytics: AnalyticsSummary = {
  total_leads: 10,
  hot_leads: 2,
  warm_leads: 3,
  cold_leads: 3,
  closed: 2,
  revenue_pipeline: 209000,
  closed_revenue: 195000,
  conversion_rate: 20.0,
  active_deals: 5,
  lead_status_distribution: [
    { name: "Hot Lead", value: 2, color: "#EF4444" },
    { name: "Warm Lead", value: 3, color: "#F59E0B" },
    { name: "Cold Lead", value: 3, color: "#6366F1" },
    { name: "Closed", value: 2, color: "#10B981" },
  ],
  weekly_revenue: [
    { week: "Week 1", revenue: 42000, target: 50000 },
    { week: "Week 2", revenue: 68000, target: 55000 },
    { week: "Week 3", revenue: 53000, target: 60000 },
    { week: "Week 4", revenue: 91000, target: 65000 },
    { week: "Week 5", revenue: 87000, target: 70000 },
    { week: "Week 6", revenue: 120000, target: 75000 },
  ],
  funnel: [
    { stage: "Prospects", count: 240, value: 1200000 },
    { stage: "Qualified", count: 142, value: 890000 },
    { stage: "Proposal", count: 78, value: 620000 },
    { stage: "Negotiation", count: 34, value: 380000 },
    { stage: "Closed Won", count: 18, value: 210000 },
  ],
  conversion_trends: [
    { month: "Jan", rate: 18.2 },
    { month: "Feb", rate: 21.5 },
    { month: "Mar", rate: 19.8 },
    { month: "Apr", rate: 24.3 },
    { month: "May", rate: 28.7 },
    { month: "Jun", rate: 31.2 },
  ],
};

export const mockInsights: Insight = {
  priority_leads: [
    {
      name: "Sarah Johnson",
      company: "TechFlow Inc",
      score: 94,
      reason: "High buying intent, demo scheduled",
      deal_value: 85000,
    },
    {
      name: "Marcus Chen",
      company: "DataVault Co",
      score: 88,
      reason: "Budget confirmed, Q4 deadline",
      deal_value: 62000,
    },
    {
      name: "Elena Rodriguez",
      company: "ScaleUp Labs",
      score: 76,
      reason: "Strong engagement, multiple touchpoints",
      deal_value: 47000,
    },
  ],
  at_risk: [
    {
      name: "James Wilson",
      company: "OldCo Corp",
      score: 32,
      reason: "No response in 14 days",
      deal_value: 28000,
    },
    {
      name: "Priya Patel",
      company: "StartRight LLC",
      score: 28,
      reason: "Budget frozen until Q1",
      deal_value: 18000,
    },
  ],
  reminders: [
    { lead: "Sarah Johnson", action: "Send customized proposal by EOD", urgency: "high" },
    { lead: "Marcus Chen", action: "Schedule executive business review", urgency: "medium" },
    { lead: "Raj Mehta", action: "Follow up on trial experience", urgency: "medium" },
  ],
  predicted_closures: [
    {
      name: "Sarah Johnson",
      probability: 87,
      expected_date: "Jun 28, 2026",
      deal_value: 85000,
    },
    {
      name: "Marcus Chen",
      probability: 72,
      expected_date: "Jul 5, 2026",
      deal_value: 62000,
    },
    {
      name: "Ava Thompson",
      probability: 61,
      expected_date: "Jul 15, 2026",
      deal_value: 34000,
    },
  ],
  strategy_suggestions: [
    "Focus Q2 outreach on Series B startups — 3x higher conversion rate",
    "Schedule demos on Tuesday-Thursday 2-4pm for 28% higher show rates",
    "Add ROI calculator to proposals — deals close 40% faster",
    "Personalize LinkedIn follow-ups within 2 hours of a meeting for best engagement",
  ],
};
